
test_that("error outside of test_that()", {
  # TODO
})
